# Generated by Django 5.2.1 on 2025-06-06 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.AddField(
            model_name='message',
            name='user_pair_id',
            field=models.CharField(default='anonymous', max_length=255),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user_pair_id', 'timestamp'], name='chat_messag_user_pa_5ee5f2_idx'),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
