# Generated by Django 5.2.1 on 2025-06-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
