# Generated by Django 5.2.1 on 2025-06-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
